var GAME_LEVELS = [
  ["  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         x           x                     x  ",
   "  x                                         xxxxxxxxxxxxx                     x  ",
   "  x                                                                           x  ",
   "  x                                                                       e   x  ",
   "  x                           xxxx                                            x  ",
   "  x                           x!!x                                            x  ",
   "  x     xx   xx    xx    xxxxxx!!xxx    xxx |  |  |  |  | xxx     xxxxxxxxxxxxx  ",
   "  x     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!!!!!!!!!!!!!!!!",
   "  x  @  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!!!!!!!!!!!!!!!!",
   "!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                             ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  x    x                                                ===x ",
   "  x e  x                                                ===x ",
   "  x    x                                                ===x ",
   "  x    x  xxxxxxx   xxxxxxxxxxx   xxxxxxxx   xxxxxxxxxxxxxxx ",
   "  x          ===x===                     x                 x ",
   "  x          ===x===                     x                 x ",
   "  x          ===x===                     x                 x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx p x ",
   "  x===                                                     x ",
   "  x===                                                     x ",
   "  x===     @                                               x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                             "],
  ["                                                                                             |    |        x",
   "            v       v       v                 v     v     v     v     v                                    x",
   "                                                                                                           x",
   "                                                                                                           x",
   "                                                                                                      x    x",
   "                                                                                                      x    x",
   "                                                                                         xx           x    x",
   "                                                                                                      x    x",
   "                                                                                                      x    x",
   "                                                                                                      x    x",
   "p                                                                                                   xxx    x",
   "                                                                                                    xxx    x",
   "x                                                                                                   xxx e  x",
   "         @                                                                                          xxx    x",
   "       xxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               xxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "               |           |      nx        nx              nx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        n x",
   "                                   x         x               x x   x   x   x   x   x   x   x    x          x",
   "      x                       x    x    x    x       = x     x n   n   n   n   n   n   n   n    x     =    x",
   "      x  |           |        x    x    x    x         x     x                                  x     x    x",
   "      xxxxxxxxxxxxxxxxxxxxxxxxx    x    x    x    =    x     x                                  x     x    x",
   "      xxxxxxxxxxxxxxxxxxxxxxxxx    x=       =x         x     x                                  v     x    x",
   "      xn           n          x    x    x    x =       x     x                                        x    x",
   "      x                       x    x    x    x         x     x                                        x    x",
   "      x    =        =        =x    x    x    x    =    x     x                                        x    x",
   "      x                            x=       =x         x     x                                        x    x",
   "      x                            x    x    x       = x     x                                        x    x",
   "      x         rxxxxx     rxxxxxxxx    x              x                                              x e  x",
   " @    x                                 x        r     x      r  r   r   r   r   r   r   r           rx    x",
   "xxxxr x   |             |             r xxxxxxxxxxxxxxxxxxxxxxxx x   x   x   x   x   x   x xxxxxxxxxxxxxxxxx",
   "!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
